"""
List of GSMArena phone URLs to scrape, organized by brand.
Add or remove URLs as needed - the scraper reads from here.

To get a URL: go to gsmarena.com, search for a phone, click on it,
then click "Opinions" tab. Copy that URL.
"""

PHONE_URLS = {
    "samsung": [
        # "https://www.gsmarena.com/samsung_galaxy_s24_ultra-reviews-12771.php",
        # "https://www.gsmarena.com/samsung_galaxy_s24-reviews-12773.php",
        # "https://www.gsmarena.com/samsung_galaxy_s23_ultra-reviews-12024.php",
        # "https://www.gsmarena.com/samsung_galaxy_s23-reviews-12082.php",
        # "https://www.gsmarena.com/samsung_galaxy_a54-reviews-12070.php",
        # "https://www.gsmarena.com/samsung_galaxy_a55-reviews-12824.php",
        # "https://www.gsmarena.com/samsung_galaxy_z_fold5-reviews-12500.php",
        # "https://www.gsmarena.com/samsung_galaxy_z_flip5-reviews-12501.php",
        # "https://www.gsmarena.com/samsung_galaxy_note20_ultra-reviews-10355.php",
        # "https://www.gsmarena.com/samsung_galaxy_m14-reviews-12233.php",
        # "https://www.gsmarena.com/samsung_galaxy_s22_ultra_5g-reviews-11251.php",
        # "https://www.gsmarena.com/samsung_galaxy_s22-reviews-11253.php",
        # "https://www.gsmarena.com/samsung_galaxy_s21_ultra_5g-reviews-10596.php",
        # "https://www.gsmarena.com/samsung_galaxy_a52-reviews-10666.php",
        # "https://www.gsmarena.com/samsung_galaxy_a52s_5g-reviews-11062.php",
        # "https://www.gsmarena.com/samsung_galaxy_a32-reviews-10662.php",
        # "https://www.gsmarena.com/samsung_galaxy_m31-reviews-10075.php",

        "https://www.gsmarena.com/samsung_galaxy_s20-reviews-9876.php",
        "https://www.gsmarena.com/samsung_galaxy_s10-reviews-9536.php",
        "https://www.gsmarena.com/samsung_galaxy_s10_plus-reviews-9535.php",
        "https://www.gsmarena.com/samsung_galaxy_note10-reviews-9787.php",
        "https://www.gsmarena.com/samsung_galaxy_note10+-reviews-9788.php",
        "https://www.gsmarena.com/samsung_galaxy_a50-reviews-9554.php",
        "https://www.gsmarena.com/samsung_galaxy_a70-reviews-9650.php",
        "https://www.gsmarena.com/samsung_galaxy_m21-reviews-10131.php",
    ],

    "iphone": [
        # "https://www.gsmarena.com/apple_iphone_15_pro_max-reviews-12548.php",
        # "https://www.gsmarena.com/apple_iphone_15_pro-reviews-12557.php",
        # "https://www.gsmarena.com/apple_iphone_15-reviews-12559.php",
        # "https://www.gsmarena.com/apple_iphone_14_pro_max-reviews-11773.php",
        # "https://www.gsmarena.com/apple_iphone_14_pro-reviews-11774.php",
        # "https://www.gsmarena.com/apple_iphone_14-reviews-11861.php",
        # "https://www.gsmarena.com/apple_iphone_13_pro_max-reviews-11089.php",
        # "https://www.gsmarena.com/apple_iphone_13-reviews-11103.php",
        # "https://www.gsmarena.com/apple_iphone_12-reviews-10509.php",
        # "https://www.gsmarena.com/apple_iphone_se_(2022)-reviews-11529.php",
        # "https://www.gsmarena.com/apple_iphone_11_pro_max-reviews-9846.php",
        # "https://www.gsmarena.com/apple_iphone_11-reviews-9848.php",
        # "https://www.gsmarena.com/apple_iphone_xr-reviews-9320.php",
        # "https://www.gsmarena.com/apple_iphone_xs_max-reviews-9319.php",

        "https://www.gsmarena.com/apple_iphone_xs-reviews-9318.php",
        "https://www.gsmarena.com/apple_iphone_8_plus-reviews-8730.php",
        "https://www.gsmarena.com/apple_iphone_7_plus-reviews-8275.php",
        "https://www.gsmarena.com/apple_iphone_6s-reviews-7242.php",
        "https://www.gsmarena.com/apple_iphone_6s_plus-reviews-7243.php",
        "https://www.gsmarena.com/apple_iphone_se-reviews-7969.php",
    ],

    "xiaomi": [
        # "https://www.gsmarena.com/xiaomi_redmi_note_12-reviews-12086.php",
        # "https://www.gsmarena.com/xiaomi_redmi_note_11-reviews-11378.php",
        # "https://www.gsmarena.com/xiaomi_redmi_note_10_pro-reviews-10662.php",
        # "https://www.gsmarena.com/xiaomi_redmi_note_10-reviews-10689.php",
        # "https://www.gsmarena.com/xiaomi_redmi_note_9_pro-reviews-10138.php",
        # "https://www.gsmarena.com/xiaomi_redmi_note_8-reviews-9818.php",
        # "https://www.gsmarena.com/xiaomi_mi_11-reviews-10663.php",
        # "https://www.gsmarena.com/xiaomi_mi_10t_pro_5g-reviews-10453.php",
        # "https://www.gsmarena.com/xiaomi_poco_x3_nfc-reviews-10377.php",
        # "https://www.gsmarena.com/xiaomi_poco_f3-reviews-10666.php",
        # "https://www.gsmarena.com/xiaomi_redmi_9-reviews-10233.php",
        # "https://www.gsmarena.com/xiaomi_redmi_note_9s-reviews-10145.php",

        "https://www.gsmarena.com/xiaomi_redmi_note_6_pro-reviews-9301.php",
        "https://www.gsmarena.com/xiaomi_redmi_note_5_pro-reviews-9081.php",
        "https://www.gsmarena.com/xiaomi_mi_8-reviews-9065.php",
        "https://www.gsmarena.com/xiaomi_mi_a2-reviews-9258.php",
        "https://www.gsmarena.com/xiaomi_redmi_6_pro-reviews-9241.php",
        "https://www.gsmarena.com/xiaomi_mi_max_3-reviews-9197.php",
        "https://www.gsmarena.com/xiaomi_redmi_5_plus_(redmi_note_5)-reviews-8973.php",
        "https://www.gsmarena.com/xiaomi_pocophone_f1-reviews-9293.php",
    ],

    "mixed": [
        # "https://www.gsmarena.com/oneplus_nord_2t-reviews-11576.php",
        # "https://www.gsmarena.com/oneplus_nord-reviews-10289.php",
        # "https://www.gsmarena.com/oneplus_8_pro-reviews-10047.php",
        # "https://www.gsmarena.com/oneplus_7t-reviews-9881.php",
        # "https://www.gsmarena.com/oppo_reno5_5g-reviews-10619.php",
        # "https://www.gsmarena.com/oppo_a74-reviews-10821.php",
        # "https://www.gsmarena.com/vivo_v21-reviews-10825.php",
        # "https://www.gsmarena.com/vivo_y20-reviews-10403.php",
        # "https://www.gsmarena.com/realme_8_pro-reviews-10711.php",
        # "https://www.gsmarena.com/realme_7-reviews-10355.php",
        # "https://www.gsmarena.com/realme_narzo_30-reviews-10889.php",
        # "https://www.gsmarena.com/huawei_p30_pro-reviews-9635.php",
        # "https://www.gsmarena.com/huawei_mate_20_pro-reviews-9343.php",
        # "https://www.gsmarena.com/nokia_8_3_5g-reviews-10271.php",
        # "https://www.gsmarena.com/oneplus_9-reviews-10643.php",
        # "https://www.gsmarena.com/oneplus_8t-reviews-10455.php",
        # "https://www.gsmarena.com/oneplus_6t-reviews-9350.php",
        # "https://www.gsmarena.com/google_pixel_6-reviews-11037.php",
        # "https://www.gsmarena.com/google_pixel_4a-reviews-10243.php",
        # "https://www.gsmarena.com/realme_x50_pro_5g-reviews-10068.php",
        # "https://www.gsmarena.com/oppo_find_x2-reviews-10042.php",
        # "https://www.gsmarena.com/huawei_p40_pro-reviews-10050.php",

        "https://www.gsmarena.com/oneplus_6-reviews-9159.php",
        "https://www.gsmarena.com/oneplus_5-reviews-8647.php",
        "https://www.gsmarena.com/google_pixel_2_xl-reviews-8856.php",
        "https://www.gsmarena.com/google_pixel_3-reviews-9335.php",
        "https://www.gsmarena.com/huawei_p20-reviews-9106.php",
        "https://www.gsmarena.com/huawei_mate_10_pro-reviews-8889.php",
        "https://www.gsmarena.com/oppo_f9_(f9_pro)-reviews-9275.php",
        "https://www.gsmarena.com/realme_2_pro-reviews-9351.php",
    ],
}

# Number of pages to scrape per phone (each page has ~30 reviews)
PAGES_PER_PHONE = 10